/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Controlador.Singleton;
import Modelo.Algoritmo;
import Modelo.Algoritmos.CSCAN;
import Modelo.Algoritmos.FIFO_PROC;
import Modelo.Algoritmos.FIFO_TRACK;
import Modelo.Algoritmos.FSCAN;
import Modelo.Algoritmos.LIFO;
import Modelo.Algoritmos.NSCAN;
import Modelo.Algoritmos.PRI;
import Modelo.Algoritmos.RSS;
import Modelo.Algoritmos.SCAN;
import Modelo.Algoritmos.SSTF;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Rigo-PC
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        agregarAlgoritmos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton_cargaProcesos = new javax.swing.JButton();
        jButton_cargarRequesiciones = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_procesos = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField_inicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_total = new javax.swing.JTextField();
        jComboBox_dir = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton_ejecutar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField_total1 = new javax.swing.JTextField();
        jButton_verGrafico = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_estadistica = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jComboBox_requisiciones = new javax.swing.JComboBox<>();
        jButton_ayuda = new javax.swing.JButton();
        jRadioButton_Uno = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_compa = new javax.swing.JTextArea();
        jButton_comparar = new javax.swing.JButton();
        jRadioButton_UnoC = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jButton_cargaProcesos.setText("Cargar Procesos");
        jButton_cargaProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cargaProcesosActionPerformed(evt);
            }
        });

        jButton_cargarRequesiciones.setText("Cargar requesiciones");
        jButton_cargarRequesiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cargarRequesicionesActionPerformed(evt);
            }
        });

        jTextArea_procesos.setEditable(false);
        jTextArea_procesos.setColumns(20);
        jTextArea_procesos.setRows(5);
        jScrollPane2.setViewportView(jTextArea_procesos);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton_cargaProcesos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_cargarRequesiciones)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cargaProcesos)
                    .addComponent(jButton_cargarRequesiciones))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("CargaDatos", jPanel1);

        jCheckBox1.setText("RSS");

        jCheckBox2.setText("PRI");

        jLabel1.setText("Basado en quién solicita:");

        jCheckBox3.setText("FIFO");

        jCheckBox4.setText("LIFO");

        jLabel2.setText("Basados en lo solicitado:");

        jCheckBox5.setText("FIFO");

        jCheckBox6.setText("SSTF");

        jCheckBox7.setText("SCAN");

        jCheckBox8.setText("C-SCAN");

        jCheckBox9.setText("N-step SCAN ");

        jCheckBox10.setText("FSCAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jCheckBox2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox4))))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Pista de inicio:");

        jLabel4.setText("Total de pistas:");

        jComboBox_dir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decremento", "Incremento" }));

        jLabel5.setText("Dirección:");

        jButton_ejecutar.setText("Ejecutar");
        jButton_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ejecutarActionPerformed(evt);
            }
        });

        jLabel6.setText("Tamaño grupos:");

        jButton_verGrafico.setText("Ver Recorrido");
        jButton_verGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_verGraficoActionPerformed(evt);
            }
        });

        jButton1.setText("Ver estadistica");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea_estadistica.setColumns(20);
        jTextArea_estadistica.setRows(5);
        jScrollPane3.setViewportView(jTextArea_estadistica);

        jButton2.setText("Reiniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton_ayuda.setText("Ayuda");
        jButton_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ayudaActionPerformed(evt);
            }
        });

        jRadioButton_Uno.setText("Uno a Uno");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_ejecutar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButton_ayuda)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField_inicio)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField_total, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBox_dir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField_total1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jRadioButton_Uno))
                                            .addComponent(jButton1))
                                        .addGap(81, 81, 81))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_verGrafico)
                                .addGap(82, 82, 82))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jComboBox_requisiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton_ejecutar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_total, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(24, 24, 24)
                                .addComponent(jComboBox_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_total1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jComboBox_requisiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton_Uno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton_ayuda)
                    .addComponent(jButton_verGrafico))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Algortimos", jPanel2);

        jCheckBox11.setText("RSS");

        jCheckBox12.setText("PRI");

        jLabel7.setText("Basado en quién solicita:");

        jCheckBox13.setText("FIFO");

        jCheckBox14.setText("LIFO");

        jLabel8.setText("Basados en lo solicitado:");

        jCheckBox15.setText("FIFO");

        jCheckBox16.setText("SSTF");

        jCheckBox17.setText("SCAN");

        jCheckBox18.setText("C-SCAN");

        jCheckBox19.setText("N-step SCAN ");

        jCheckBox20.setText("FSCAN");

        jTextArea_compa.setColumns(20);
        jTextArea_compa.setRows(5);
        jScrollPane4.setViewportView(jTextArea_compa);

        jButton_comparar.setText("Ejecutar Comparación");
        jButton_comparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_compararActionPerformed(evt);
            }
        });

        jRadioButton_UnoC.setText("Uno a Uno");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox19)
                    .addComponent(jCheckBox16)
                    .addComponent(jCheckBox17)
                    .addComponent(jCheckBox18)
                    .addComponent(jCheckBox15)
                    .addComponent(jLabel8)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox13)
                    .addComponent(jCheckBox20)
                    .addComponent(jCheckBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton_UnoC)
                        .addGap(176, 176, 176))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jButton_comparar)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox14)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox20)
                        .addGap(18, 111, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton_UnoC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jButton_comparar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Comparaciones", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.jCheckBox1.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(0);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(0);
        }
        if(this.jCheckBox2.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(1);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(1);
        }
        if(this.jCheckBox3.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(2);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(2);
        }
        if(this.jCheckBox4.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(3);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(3);
        }
        if(this.jCheckBox5.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(4);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(4);
        }
        if(this.jCheckBox6.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(5);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(5);
        }
        if(this.jCheckBox7.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(6);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(6);
        }
        if(this.jCheckBox8.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(7);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(7);
        }
        if(this.jCheckBox9.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(8);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(8);
        }
        if(this.jCheckBox10.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(9);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(9);
        }
        String est;
        if(jRadioButton_Uno.isSelected()){
            est = Singleton.getInstance().getControlador().verEstadisticasUno();
        }else{
            est = Singleton.getInstance().getControlador().verEstadisticas();
        }
        this.jTextArea_estadistica.setText(est);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_verGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_verGraficoActionPerformed
        // TODO add your handling code here:
        int tipo=0;
        if(this.jRadioButton_Uno.isSelected()){
            tipo=1;
        }
        if(this.jCheckBox1.isSelected()){
            Grafico grafico = new Grafico("RSS",Singleton.getInstance().getControlador()
                .getGestorAlgoritmos().get(0).getResultados(),tipo);
            grafico.show();
        }
        if(this.jCheckBox2.isSelected()){
            Grafico grafico = new Grafico("PRI",Singleton.getInstance().getControlador()
                .getGestorAlgoritmos().get(1).getResultados(),tipo);
            grafico.show();
        }
        if(this.jCheckBox3.isSelected()){
            Grafico grafico = new Grafico("FIFO",Singleton.getInstance().getControlador()
                .getGestorAlgoritmos().get(2).getResultados(),tipo);
            grafico.show();
        }
        if(this.jCheckBox4.isSelected()){
            Grafico grafico = new Grafico("LIFO",Singleton.getInstance().getControlador()
                .getGestorAlgoritmos().get(3).getResultados(),tipo);
            grafico.show();
        }
        if(this.jCheckBox5.isSelected()){
            Grafico grafico = new Grafico("FIFO",Singleton.getInstance().getControlador()
                .getGestorAlgoritmos().get(4).getResultados(),tipo);
            grafico.show();
        }
        if(this.jCheckBox6.isSelected()){
            Grafico grafico = new Grafico("SSTF",Singleton.getInstance().getControlador()
                .getGestorAlgoritmos().get(5).getResultados(),tipo);
            grafico.show();
        }
        if(this.jCheckBox7.isSelected()){
            Grafico grafico = new Grafico("SCAN",Singleton.getInstance().getControlador()
                .getGestorAlgoritmos().get(6).getResultados(),tipo);
            grafico.show();
        }
        if(this.jCheckBox8.isSelected()){
            Grafico grafico = new Grafico("-SCAN",Singleton.getInstance().getControlador()
                .getGestorAlgoritmos().get(7).getResultados(),tipo);
            grafico.show();
        }
        if(this.jCheckBox9.isSelected()){
            Grafico grafico = new Grafico("N-step SCAN",Singleton.getInstance().getControlador()
                .getGestorAlgoritmos().get(8).getResultados(),tipo);
            grafico.show();
        }
        if(this.jCheckBox10.isSelected()){
            Grafico grafico = new Grafico("FSCAN",Singleton.getInstance().getControlador()
                .getGestorAlgoritmos().get(9).getResultados(),tipo);
            grafico.show();
        }

    }//GEN-LAST:event_jButton_verGraficoActionPerformed

    private void jButton_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ejecutarActionPerformed
        // TODO add your handling code here:

        cambiarEstadoAlgoritmos();

        String inicio = this.jTextField_inicio.getText();
        String total = this.jTextField_total.getText();
        String grupos = this.jTextField_total1.getText();
        
        
        int direccion = 0 ;
        String direccionString = (String)this.jComboBox_dir.getSelectedItem();
        if(direccionString.equals("Incremento")){
            direccion = 1; 
            
        }
        else{
            direccion = 0;
        }

        System.out.println("Direccion: " + direccion);
        
        
        
        if(!inicio.equals("")){
            if(!total.equals("")){
                if(!grupos.equals("")){
                    String requisicion = (String)this.jComboBox_requisiciones.getSelectedItem();
                    if(!requisicion.isEmpty()){
                        int re = Integer.parseInt(requisicion);
                        Singleton.getInstance().getControlador().ejecutarAlgoritmos(re,
                            Integer.parseInt(inicio),
                            Integer.parseInt(total),
                            direccion,
                            Integer.parseInt(grupos));
                    }
                    mensajeDialog("Se ejecutaron los algoritmos.", "Ejecución existosa.");
                }else{
                    mensajeDialog("Complete el tamaño grupos", "Datos incompletos");
                }
            }else{
                mensajeDialog("Complete el total", "Datos incompletos");
            }
        }else{
            mensajeDialog("Complete el inicio", "Datos incompletos");
        }

    }//GEN-LAST:event_jButton_ejecutarActionPerformed

    private void jButton_cargarRequesicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cargarRequesicionesActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(null);
        // int returnValue = jfc.showSaveDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();

            Singleton.getInstance().getControlador().leerRequisiciones(selectedFile);

            String requis = Singleton.getInstance().getControlador().imprimirListaRequisiciones();
            this.jTextArea1.setText(requis);
        }
    }//GEN-LAST:event_jButton_cargarRequesicionesActionPerformed

    private void jButton_cargaProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cargaProcesosActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(null);
        // int returnValue = jfc.showSaveDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();

            Singleton.getInstance().getControlador().leerProcesos(selectedFile);

            String procesos = Singleton.getInstance().getControlador().getListaProcesos().ImprimirColaProcesos();

            this.jTextArea_procesos.setText(procesos);
        }
    }//GEN-LAST:event_jButton_cargaProcesosActionPerformed

    private void jButton_compararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_compararActionPerformed
        // TODO add your handling code here:
        ArrayList<Integer> select = new ArrayList<>();
        if(this.jCheckBox11.isSelected()){
            select.add(0);
        }
        if(this.jCheckBox12.isSelected()){
            select.add(1);
        }
        if(this.jCheckBox13.isSelected()){
            select.add(2);
        }
        if(this.jCheckBox14.isSelected()){
            select.add(3);
        }
        if(this.jCheckBox15.isSelected()){
            select.add(4);
        }
        if(this.jCheckBox16.isSelected()){
            select.add(5);
        }
        if(this.jCheckBox17.isSelected()){
            select.add(6);
        }
        if(this.jCheckBox18.isSelected()){
            select.add(7);
        }
        if(this.jCheckBox19.isSelected()){
            select.add(8);
        }
        if(this.jCheckBox20.isSelected()){
            select.add(9);
        }
        if(select.size()>0){
            if(this.jRadioButton_UnoC.isSelected()){
                //System.out.println(select.toString());
                String str = Singleton.getInstance().getControlador().verComparacionesAlgoritmoUno(select);
                this.jTextArea_compa.setText(str);
                GraficoComparativo grafico = new GraficoComparativo(select,
                        Singleton.getInstance().getControlador().getGestorAlgoritmos(),1);
               grafico.show();
            }else{
                //System.out.println(select.toString());
                String str = Singleton.getInstance().getControlador().verComparacionesAlgoritmo(select);
                this.jTextArea_compa.setText(str);
                GraficoComparativo grafico = new GraficoComparativo(select,
                        Singleton.getInstance().getControlador().getGestorAlgoritmos(),0);
               grafico.show();
            }
            
        }else{
            mensajeDialog("Seleccion un algoritmo.", "Datos Incompletos");
        }
        
    }//GEN-LAST:event_jButton_compararActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Singleton.getInstance().getControlador().eliminarResultados();
        mensajeDialog("Datos de resultados eliminados.", "Correcto.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        int select = this.jTabbedPane1.getSelectedIndex();
        if(select==1){
            cargarRequisiciones();
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ayudaActionPerformed
        // TODO add your handling code here:
        String ayudaSensitiva = "";
        
        //Descripción:
        ayudaSensitiva+="DESCRIPCIÓN:"
                +"El sistema debe contar con 2 partes fundamentales:\n"
                + "+Carga de procesos.\n"
                + "+Carga de requisiciones(Las cuales corresponden a filas).\n"
                + "Luego de cargado estos datos se puede ejecutar corridas de algoritmos de Scheduling"
                + "con una cierta configuración de datos.\n"
                + "Los algoritmos son ejecutados con requisiciones que fueron cargadas generando un ordenamiento,"
                + "el cual se puede visualizar de dos manera:\n"
                + "Individual: Se presenta una grafica que representa el recorrido del algortimo, ademas de estadisticas"
                + "individuales.\n"
                + "Comparativo: Se presenta una grafica con los diferentes algoritmos y todas sus estadisticas.\n"
                + "Por ultimo, se puede visualizar los resultados por:\n"
                + "-Ejecución completa.\n"
                + "-Ejecución por partes.\n\n";
        
        
        //Algoritmos
        ayudaSensitiva+="ALGORITMOS:\n";
        if(this.jCheckBox1.isSelected()){
            ayudaSensitiva += "RSS: Algoritmo de scheduling que elige un proceso aleatoriamente y luego ejecuta"
                    +"las referencias a pista del proceso, esto se ejecuta para cada proceso.\n";
        }
        if(this.jCheckBox2.isSelected()){
            ayudaSensitiva+="PRI: Algoritmo de scheduling que se basa en la prioridad de los procesos para ordenar"
                    +"cada una de las referencias a pista.\n";
        }
        if(this.jCheckBox3.isSelected()){
            ayudaSensitiva+="FIFO: Algoritmo de scheduling que ordena las referencias a pista de acuerdo al orden "+
                    "de creación de los procesos.\n";
        }
        if(this.jCheckBox4.isSelected()){
            ayudaSensitiva+="LIFO: Algoritmo de scheduling que ordena las referencias a pista de acuerdo al orden"
                    +" de creación pero basado en el mas reciente.\n";
        }
        if(this.jCheckBox5.isSelected()){
            ayudaSensitiva+="FIFO: Algoritmo de scheduling que ordena las referencias a pista de acuerdo al orden"+
                    " establecida en la requisiciones.\n";
        }
        if(this.jCheckBox6.isSelected()){
            ayudaSensitiva+="SSTF: Algoritmo de scheduling que ordena las referencias a pista de acuerdo a la mas cercana"+
                    " a la pista de inicio establecida o a la ultima que se ejecuto de esta manera para cada solicitud.\n";
        }
        if(this.jCheckBox7.isSelected()){
            ayudaSensitiva+="SCAN: Algoritmo de scheduling que ordena las referencias a pista de acuerdo a la siguiente"+
                    " solicitud más cercana respetando la dirección en forma de elavador:\n"
                    +"\tIncremento: hacia arriaba el más cercano.\n"
                    +"\tDecremento: hacia abajo el más cercano.\n";
        }
        if(this.jCheckBox8.isSelected()){
            ayudaSensitiva+="C-SCAN: Algoritmo de scheduling que ordena las referencias a pista de acuerdo a la siguiente"+
                    " solicitud más cercana respetando la dirección en forma de circular:\n"
                    +"\tIncremento: hacia arriaba el más cercano.\n"
                    +"\tDecremento: hacia abajo el más cercano.\n";
        }
        if(this.jCheckBox9.isSelected()){
            ayudaSensitiva+="N-step-SCAN: Algoritmo de scheduling que ordena las referencias a pista de acuerdo a la siguiente"+
                    " solicitud más cercana respetando la dirección pero que crea grupos de un tamaño N:\n"
                    +"\tIncremento: hacia arriaba el más cercano.\n"
                    +"\tDecremento: hacia abajo el más cercano.\n";
        }
        if(this.jCheckBox10.isSelected()){
            ayudaSensitiva+="C-SCAN: Algoritmo de scheduling que ordena las referencias a pista de acuerdo a la siguiente"+
                    " solicitud más cercana respetando la dirección en forma de circular:\n"
                    +"\tIncremento: hacia arriaba el más cercano.\n"
                    +"\tDecremento: hacia abajo el más cercano.\n"
                    +"Pero adicionalmente cuenta con una segunda lista donde se encuentran los nuevos seleccionados.\n";
        }
        
        mensajeDialog(ayudaSensitiva, "Ayuda Sensitiva.");
    }//GEN-LAST:event_jButton_ayudaActionPerformed

    public void agregarAlgoritmos(){
        Algoritmo algoritmo = new RSS("RSS");
        Singleton.getInstance().getControlador().agregarAlgoritmo(algoritmo);
        
        algoritmo = new PRI("PRI");
        Singleton.getInstance().getControlador().agregarAlgoritmo(algoritmo);
        
        algoritmo = new FIFO_PROC("FIFO_PROC");
        Singleton.getInstance().getControlador().agregarAlgoritmo(algoritmo);
        
        algoritmo = new LIFO("LIFO");
        Singleton.getInstance().getControlador().agregarAlgoritmo(algoritmo);
        
        algoritmo = new FIFO_TRACK("FIFO_TRACK");
        Singleton.getInstance().getControlador().agregarAlgoritmo(algoritmo);
        
        algoritmo = new SSTF("SSTF");
        Singleton.getInstance().getControlador().agregarAlgoritmo(algoritmo);
        
        algoritmo = new SCAN("SCAN");
        Singleton.getInstance().getControlador().agregarAlgoritmo(algoritmo);
        
        algoritmo = new CSCAN("CSCAN");
        Singleton.getInstance().getControlador().agregarAlgoritmo(algoritmo);
        
        algoritmo = new NSCAN("NSCAN");
        Singleton.getInstance().getControlador().agregarAlgoritmo(algoritmo);
        
        algoritmo = new FSCAN("FSCAN");
        Singleton.getInstance().getControlador().agregarAlgoritmo(algoritmo);
    }
    
    public void cambiarEstadoAlgoritmos(){
        if(this.jCheckBox1.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(0);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(0);
        }
        if(this.jCheckBox2.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(1);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(1);
        }
        if(this.jCheckBox3.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(2);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(2);
        }
        if(this.jCheckBox4.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(3);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(3);
        }
        if(this.jCheckBox5.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(4);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(4);
        }
        if(this.jCheckBox6.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(5);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(5);
        }
        if(this.jCheckBox7.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(6);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(6);
        }
        if(this.jCheckBox8.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(7);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(7);
        }
        if(this.jCheckBox9.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(8);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(8);
        }
        if(this.jCheckBox10.isSelected()){
            Singleton.getInstance().getControlador().activarAlgoritmo(9);
        }else{
            Singleton.getInstance().getControlador().desactivarAlgoritmo(9);
        }
    }
    
    public void mensajeDialog(String mensaje, String tituloBarra){
        
        JOptionPane.showMessageDialog(null, mensaje, tituloBarra, JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * Metodo que permite cargar las aplicaciones en JList
     * @param jList 
     */
    public void cargarRequisiciones(){
        
        int num = Singleton.getInstance().getControlador().getCantidadRequisiciones();
        this.jComboBox_requisiciones.removeAllItems();
        
        for (int i=0;i<num;i++) {
            this.jComboBox_requisiciones.addItem(String.valueOf(i));
        }
        

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_ayuda;
    private javax.swing.JButton jButton_cargaProcesos;
    private javax.swing.JButton jButton_cargarRequesiciones;
    private javax.swing.JButton jButton_comparar;
    private javax.swing.JButton jButton_ejecutar;
    private javax.swing.JButton jButton_verGrafico;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox_dir;
    private javax.swing.JComboBox<String> jComboBox_requisiciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton_Uno;
    private javax.swing.JRadioButton jRadioButton_UnoC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea_compa;
    private javax.swing.JTextArea jTextArea_estadistica;
    private javax.swing.JTextArea jTextArea_procesos;
    private javax.swing.JTextField jTextField_inicio;
    private javax.swing.JTextField jTextField_total;
    private javax.swing.JTextField jTextField_total1;
    // End of variables declaration//GEN-END:variables
}
